#!/bin/bash

set -euo pipefail

prompt_lv=1     # 0 = never, 1 = when write-protected, 2 = once when recursively or more than 3 files, 3 = before every operation
dir_op=0        # 0 = no operating on directories, 1 = only empty dir, 2 = all dir
verbose=0       # boolean variable
mode=0          # 0 = trash mode, 1 = rm mode, 2 = dry run
no_preserve_root=0      # boolean variable

targets=()      # operation targets

crash() {
    local msg="$1"
    local code="${2:-1}"

    if [[ -n "$msg" ]]; then
        echo -e "rm: $msg" >&2
    fi

    exit "$code"
}

askyn() {
    local answer
    read -p "rm: $1 " answer
    case "$answer" in
        y* | Y*) return 1 ;;
              *) return 0 ;;
    esac
}

printhelp() {
    echo "See '\\rm --help' for usage"
    echo "Additionally:"
    echo "      Use '--now' to invoke regular 'rm' and delete immediately"
    echo "      Use '--dry-run' to do checks only"
    echo "Note:"
    echo "      '--recursive' will NOT trash files recursively, only allows non-empty directories to be trashed."
    echo "                    But it will however recursively check the directory before trashing."
    echo "      Note that without '--now', rm-trash will refuse to operate on mount points or non-trashable targets"
    exit 0
}

printver() {
    echo "rm-trash version 1.0.0"
    echo "A drop-in interactive replacement for 'rm' that trashes instead of deleting"
    echo "Licensed under the MIT License <https://opensource.org/licenses/MIT>"
    echo "Made by fluf <https://github.com/BlackFuffey>"
    exit 0
}

readargs() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            # Long options
            --*)  
                case "$1" in
                        --force) prompt_lv=0    ;;
                  --interactive) prompt_lv=3    ;;

                          --dir) dir_op=1       ;;
                    --recursive) dir_op=2       ;;

                          --now) mode=1         ;;
                      --dry-run) mode=2         ;;

             --no-preserve-root) no_preserve_root=1 ;;

                      --verbose) verbose=1      ;;

                      --version) printver       ;;
                         --help) printhelp      ;;

                    --interactive=*)
                        local when="${1#--interactive=}"  # Strip prefix to get value
                        case "$when" in
                           never) prompt_lv=0 ;;
                            once) prompt_lv=2 ;;
                          always) prompt_lv=3 ;;

                               *) crash "invalid option '$when' for --interactive" ;;
                        esac
                        ;;

                    # Does not have any effect as these are the default
                    --one-file-system) ;;
                    --preserve-root) ;;
                    --preserve-root=all) ;;

                    *) crash "invalid argument '$1'"
                esac 
                ;;

            # Short options
            -*)   
                opts="${1:1}"  # Strip single dash
                for ((i=0; i<${#opts}; i++)); do
                    opt="${opts:$i:1}"
                    case "$opt" in
                        f) prompt_lv=0  ;;
                        I) prompt_lv=2  ;;
                        i) prompt_lv=3  ;;

                        d) dir_op=1     ;;
                        r) dir_op=2     ;;
                        R) dir_op=2     ;;

                        v) verbose=1    ;;

                        *) crash "invalid argument -- '$opt'" ;;
                    esac
                done
                ;;

            # targets
            *) targets+=("$1") ;;
        esac
        shift
    done
}

listmount() {
    if [ -z "$1" ]; then
        crash "internal error: attempted to listmount empty string" 70
    fi

    findmnt -rn --output TARGET | grep "^$(realpath "$1")(/|$)"
}

refuse() {
    echo "rm: cannot trash $1: $2" >&2
}

describe() {
    if [[ ! -e "$1" ]]; then
        crash "internal error: attempted to describe invalid target '$1'"
    fi

    local desc=""

    if [[ ! -w $1 ]]; then
        desc="write-protected "
    fi

    if [[ -d $1 ]]; then
        desc="${desc}directory"
        echo "$desc"
        return
}

checkdir() {
    [ ! -d $1 ] && crash "internal error: attempted to checkdir non directory target '$1'"

    
}

main() {
    readargs "$@"
    
    local asked = 0     # boolean variable

    if [[ $no_preserve_root -eq 1 && $mode -ne 1 ]]; then
        crash "'--no-preserve-root' can only be used with '--now'"
    fi

    if [ ${#targets[@]} -eq 0 ]; then 
        crash "no target specified"
    fi

    if [ "$prompt_lv" -eq 2 ]; then
        askyn "trash ${#my_list[@]} targets$([ "$dir_op" -eq 2 ] && " recursively")?"
        [ $? -eq 0 ] && exit 0
    fi
        

    for item in "${targets[@]}"; do
        if [ ! -e "$item" ]; then
            refuse $item "no such file or directory"
            continue
        fi

        local mntlist=$(listmount "$item")

        if [ -n "$mntlist" ]; then
            refuse $item "refuse to operate on mountpoint(s): $(echo "$mntlist" | sed 's/^/    /')"
            continue
        fi

        if [ "$prompt_lv" -be 1 ]; then
            [ -d "$item" ] && checkdir "$item" && continue

            if [ ! -w "$item" || "$prompt_lv" -eq 3 ]; then
                askyn "trash $(describe "$item")?"
                [ $? -eq 0 ] && targets[$i]="" && continue
            fi
        fi

            
                        
    done
}

main "$@"
